/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    401: typeof import('./src/shared/components/error/401.vue')['default']
    404: typeof import('./src/shared/components/error/404.vue')['default']
    AboutView: typeof import('./src/modules/about/views/AboutView.vue')['default']
    AppTheme: typeof import('./src/shared/components/theme/AppTheme.vue')['default']
    EntityFormExample: typeof import('./src/modules/examples/views/EntityFormExample.vue')['default']
    ExamplesIndex: typeof import('./src/modules/examples/views/ExamplesIndex.vue')['default']
    F7AccordionContent: typeof import('framework7-vue')['f7AccordionContent']
    F7App: typeof import('framework7-vue')['f7App']
    F7Badge: typeof import('framework7-vue')['f7Badge']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Chip: typeof import('framework7-vue')['f7Chip']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7LoginScreenTitle: typeof import('framework7-vue')['f7LoginScreenTitle']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Popup: typeof import('framework7-vue')['f7Popup']
    F7Preloader: typeof import('framework7-vue')['f7Preloader']
    F7Searchbar: typeof import('framework7-vue')['f7Searchbar']
    F7Segmented: typeof import('framework7-vue')['f7Segmented']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    HomeView: typeof import('./src/modules/home/views/HomeView.vue')['default']
    KyselyQueryExample: typeof import('./src/modules/examples/views/KyselyQueryExample.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
  }
}
