/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    F7App: typeof import('framework7-vue')['f7App']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7LoginScreenTitle: typeof import('framework7-vue')['f7LoginScreenTitle']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Segmented: typeof import('framework7-vue')['f7Segmented']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    HomeView: typeof import('./src/modules/home/views/HomeView.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
  }
}
